#!/bin/bash
source /usr/local/sbin/base-script
clear
$GRN7 
echo -e "$GRN7 ╔═══╦╗───╔═══╦═══╦╗─╔╗"
echo -e "$GRN7 ║╔══╣║───║╔═╗║╔═╗║║─║║"
echo -e "$GRN7 ║╚══╣║╔══╣╚══╣╚══╣╚═╝║"
echo -e "$GRN7 ║╔══╣║║╔╗╠══╗╠══╗║╔═╗║"
echo -e "$GRN7 ║║──║╚╣╔╗║╚═╝║╚═╝║║─║║"
echo -e "$GRN7 ╚╝──╚═╩╝╚╩═══╩═══╩╝─╚╝"
echo -e "$GRN6 ╔═╗╔═╗"
echo -e "$GRN5 ║║╚╝║║"
echo -e "$GRN4 ║╔╗╔╗╠══╦═╗╔╗╔╗"
echo -e "$GRN3 ║║║║║║║═╣╔╗╣║║║"
echo -e "$GRN2 ║║║║║║║═╣║║║╚╝║"
echo -e "$GRN1 ╚╝╚╝╚╩══╩╝╚╩══╝"
echo -e ""
echo -e ""
echo -e "$GRN1 [1] Mengelola Akun "
echo -e ""
echo -e "$GRN2 [2] Mengelola Server "
echo -e ""
echo -e "#GRN3 [3] Opsi Lanjutan "
echo -e ""
echo -e "$GRN5 [4] Keluar"
echo -e ""
read -p "$(echo -e " Tentukan Pilihanmu\e[32m [\e[0m1-5\e[32m]\e[0m: ")" Menu
echo -e ""
sleep 2
clear
case $menu in
		1)
		clear
		accounts
		exit
		;;
		2)
		clear
		server
		exit
		;;
		3)
		clear
		options
		exit
		;;
		4)
		clear
		exit
		;;
	esac
